source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'TNKFoundation_Example', :exclusive => true do
  pod "TNKFoundation", :path => "../"
end

target 'TNKFoundation_Tests', :exclusive => true do
  pod "TNKFoundation", :path => "../"
end
